#ifndef _CTYPE_CPTR_CTRLACTION_
#define _CTYPE_CPTR_CTRLACTION_

#include "ctype_cptr_primitives_vecs.h"

// ctype used to store the input to the system.
// Data represent the thrust and the torque generated by the propellers
// in the copter ref frame.

struct cptr_ctrlaction_t {
  struct   cptr_scalar_t thrust ;
  struct   cptr_vec3d_t  torque ;
  char*    type                 ;
};

#endif

